### PR TITLE
Pull from me

### PR DESCRIPTION
**Pull request by rishabhjoshi**
Pull these files from me.

### CODE REVIEW

**Comment by sharmaeklavya2** [comment]
There are a few things which you need to fix:
- There are too many entries in `.gitignore`. Change them to just `*~`.
- The link to your github account is incorrect. Github is not on www.
- The link in your markdown is not clickable. The correct syntax for this is `[URL](text_to_display)`.

Did you generate an HTML file from the markdown for previewing? If no then you can do so now. If you are using Ubuntu, use the `markdown` command. Install it from Ubuntu's repositoriy and run it like this

`markdown RishabhJoshi.md > RishabhJoshi`

**Comment by rishabhjoshi** [comment]
oh.. Okay.. Ill change the .gitignore file.
Ill change www too.
Thanks

**Comment by rishabhjoshi** [comment]
The markdown command gives no output on the terminal. 
What should it do ideally?

**Comment by rishabhjoshi** [comment]
Ignore the last msg. What should I do to make my link work? Ive removed www.. but its still not working.

**Comment by sharmaeklavya2** [comment]
Sorry the markdown format for links is `[text_to_display](URL)`.

**Comment by rishabhjoshi** [comment]
have my latest commits come to u.. i cant seem to give a pull request

**Comment by sharmaeklavya2** [comment]
Yes they have come.

**Pull request merged**
